sourcegraph/deploy-sourcegraph-helm

sourcegraph/templates/cadvisor/cadvisor.ClusterRole.yaml
sourcegraph/templates/cadvisor/cadvisor.ClusterRoleBinding.yaml
sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml
sourcegraph/templates/cadvisor/cadvisor.PodSecurityPolicy.yaml
sourcegraph/templates/cadvisor/cadvisor.ServiceAccount.yaml
sourcegraph/templates/codeinsights-db/codeinsights-db.ConfigMap.yaml
sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
sourcegraph/templates/codeinsights-db/codeinsights-db.PersistentVolumeClaim.yaml
sourcegraph/templates/codeinsights-db/codeinsights-db.Service.yaml
sourcegraph/templates/codeintel-db/codeintel-db.ConfigMap.yaml
sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
sourcegraph/templates/codeintel-db/codeintel-db.PersistentVolumeClaim.yaml
sourcegraph/templates/codeintel-db/codeintel-db.Service.yaml
sourcegraph/templates/grafana/grafana.StatefulSet.yaml
sourcegraph/templates/jaeger/jaeger-collector.Service.yaml
sourcegraph/templates/jaeger/jaeger-query.Service.yaml
sourcegraph/templates/jaeger/jaeger.Deployment.yaml
sourcegraph/templates/pgsql/pgsql.ConfigMap.yaml
sourcegraph/templates/pgsql/pgsql.Deployment.yaml
sourcegraph/templates/pgsql/pgsql.PersistentVolumeClaim.yaml
sourcegraph/templates/pgsql/pgsql.Service.yaml
sourcegraph/templates/prometheus/prometheus.ClusterRole.yaml
sourcegraph/templates/prometheus/prometheus.ClusterRoleBinding.yaml
sourcegraph/templates/prometheus/prometheus.ConfigMap.yaml
sourcegraph/templates/prometheus/prometheus.Deployment.yaml
sourcegraph/templates/prometheus/prometheus.PersistentVolumeClaim.yaml
sourcegraph/templates/prometheus/prometheus.Service.yaml
sourcegraph/templates/prometheus/prometheus.ServiceAccount.yaml
sourcegraph/templates/redis/redis-store.Deployment.yaml
sourcegraph/values.yaml

Many features missing from this pass, and there's a lot of inconsistency between the different deployments. As more functionality gets built in we can maybe introduce a "template template".

Finish first pass on deployments

---

sourcegraph/templates/_tracing.tpl
sourcegraph/templates/jaeger/jaeger-collector.Service.yaml
sourcegraph/templates/jaeger/jaeger-query.Service.yaml
sourcegraph/templates/jaeger/jaeger.Deployment.yaml
sourcegraph/values.yaml

I can't decide whether `tracing` or `jaeger` is the best name here. Tracing seems more descriptive, but since I left the resource names / folder as `jaeger` maybe it's just confusing?

Rename jaeger to tracing for consistency

---

sourcegraph/templates/_helpers.tpl
sourcegraph/templates/frontend/sourcegraph-frontend.Ingress.yaml
sourcegraph/values.yaml

Mostly documentation of the range of configuration options in the values file.
Two unrelated minor fixes:
- Eliminate hardcoding of TLS host for frontend ingress
- Remove unused fullname function

Document values file

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.37.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.37.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/30051)

release: sourcegraph@3.37.0

---

charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Same as https://github.com/sourcegraph/deploy-sourcegraph/pull/4095 but for helm.
Diffed the rendered manifests and confirmed they look the same as the deploy-sourcegraph PR.

Set default resource requests/limits on the migrator container

---

.github/PULL_REQUEST_TEMPLATE.md
TEST.md

this is a test
close https://github.com/sourcegraph/sourcegraph/issues/32175

Add maual testing guide

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml

I am looking to get helm working on dogfood and the duplicated labels from jaeger deployment is blocking me, so I might as well roll a new one out ;)
Release PR, NA

sourcegraph: release 0.5.0

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.38.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.38.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/31768)
Autogenerated by release tooling.

release: sourcegraph@3.38.0

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml

also backfill changelog for `0.6.0`
New release

sourcegraph: release 0.7.0

---

charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/README.md.gotmpl
charts/sourcegraph/README.md
charts/sourcegraph/README.md.gotmpl

N/A, docs change
close https://github.com/sourcegraph/sourcegraph/issues/32791

Pin chart version in docs

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Depends on
docs
close https://github.com/sourcegraph/sourcegraph/issues/33017

Add docs for `gitserver.sshSecret`

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.39.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.39.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/32836)

release: sourcegraph@3.39.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

When we created the release/3.39 branch we updated the chart versions. This needs to be merged back into main so that future releases are also updated.
We'll need to modify the release process to include this step automatically - maybe by creating another PR?
Chart publishes to insiders repo with the 3.39 version number.

Merge release into main

---

charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/README.md.gotmpl

This readme needs a deeper edit to move information into the official docs, but we should update the repo URL in the meantime.
Doc review

Quick fix for repo reference on migrator README

---

charts/sourcegraph/CHANGELOG.md

Update changelog now that 3.39 is published.
None, docs only. We do need to fix the release process to automatically update this, though.

Fix changelog

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Manually update changelog to include the patch release and update the chart versions in main (still need to fix the release tooling to auto-update this).
None, doc change only.

Update changelog for 3.39.1, chart version in main

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.40.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/34255)
n/a

release: sourcegraph@3.40.0

---

.github/workflows/pr-auditor.yml

Use Go 1.18 for pr-auditor

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.40.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36218)
n/a

release: sourcegraph@3.40.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.40.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.40.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/36790)

release: sourcegraph@3.40.2

---

charts/sourcegraph/CHANGELOG.md

Update 3.40.2-rev.1 changelog

---

scripts/ci/install-helm-env.sh

Run update first to fix CI

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.41.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/37183)

release: sourcegraph@3.41.0

---

.github/PULL_REQUEST_TEMPLATE.md
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

None, just backporting release

Update changelog for 3.41

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.41.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.41.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38644)

release: sourcegraph@3.41.1

---

.github/workflows/helm_lint_test.yml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/templates/tests/test-connection.yaml
ci/override.yaml

- Add icons to please helm lint
- Add Github workflow to install and test helm
Manual review and github actions

Add ci validation

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.42.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/38119)

release: sourcegraph@3.42.0

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@3.42.0
n/a

changelog: cut sourcegraph@3.42.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.42.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39596)

release: sourcegraph@3.42.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Release 3.42.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.42.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.42.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/40031)

release: sourcegraph@3.42.2

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release 3.42.2

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@3.43.0
n/a

changelog: cut sourcegraph@3.43.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.43.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/39333)

release: sourcegraph@3.43.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.43.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/40986)

release: sourcegraph@3.43.1

---

charts/sourcegraph/CHANGELOG.md

Add changelog entry for 3.43.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Following the guide, this has to be cherry-picked onto main. 
Docs

release: sourcegraph@3.43.1 (#170)

---

charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/templates/searcher/searcher.Deployment.yaml
charts/sourcegraph/templates/symbols/symbols.Deployment.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml

keep things dry

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 3.43.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-3.43.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41485)

release: sourcegraph@3.43.2

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release-3.43.2 docs updates

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Release of `3.43.2` merged some values that deprecate in 4.0 back in `main`.
None needed

Fixup patch release merge

---

charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml

Needed to mount volumes in `extraContainers` definitions.
Tested with `helm template`

Add `extraVolumes` template to migrator Job

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@4.0.0
n/a

changelog: cut sourcegraph@4.0.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41759)

release: sourcegraph@4.0.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This cherry-picks the release PR from the `release/4.0` branch as described in [the tracking issue](https://github.com/sourcegraph/sourcegraph/issues/41759)
Manually scanned the diff to ensure it applied correctly.

Cherry pick 2126e8ca from release/4.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/42112)

release: sourcegraph@4.0.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Cherry-picks release commit from `release/4.0` branch as described [here](https://github.com/sourcegraph/sourcegraph/issues/42112)
N/A

release: sourcegraph@4.0.1 (#185)

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@4.1.1 (#196)

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43612)

release: sourcegraph@4.1.2

---

charts/sourcegraph/CHANGELOG.md

4.1.2 Changelog update

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@4.1.2 (#199)

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.1.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/44078)

release: sourcegraph@4.1.3

---

charts/sourcegraph/CHANGELOG.md

4.1.3 Changelog update

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Release process cherry-picking

release: sourcegraph@4.1.3 (#210)

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@4.2.0
n/a

changelog: cut sourcegraph@4.2.0

---

charts/sourcegraph/templates/otel-collector/otel-agent.ConfigMap.yaml
charts/sourcegraph/templates/otel-collector/otel-collector.ConfigMap.yaml

Once the following change lands, these helm charts will need to be updated
- https://github.com/sourcegraph/sourcegraph/pull/44543
Use these charts to deploy scaletesting

update port to be endpoint for 0.65 collector upgrade

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.2.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.2.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/43423)

release: sourcegraph@4.2.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@4.2.0 (#215)

---

charts/sourcegraph/templates/cadvisor/cadvisor.ClusterRole.yaml
charts/sourcegraph/templates/cadvisor/cadvisor.ClusterRoleBinding.yaml

Companion PR to https://github.com/sourcegraph/deploy-sourcegraph/pull/4205
Test against a GCP k8s cluster to verify nothing breaks.

cadvisor clusterrole and clusterrolebinding only necessary if using podsecuritypolicy

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.2.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.2.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45373)

release: sourcegraph@4.2.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.3.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45566)

release: sourcegraph@4.3.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

cherry pick release onto main

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.3.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46161)

release: sourcegraph@4.3.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Cherry pick 4.3.1 release

---

charts/sourcegraph/CHANGELOG.md

Release: add changelog entries for 4.3.0 and 4.3.1

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@4.4.0
n/a

changelog: cut sourcegraph@4.4.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.4.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/45780)

release: sourcegraph@4.4.0

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@4.4.0 (#231)

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.4.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/46931)

release: sourcegraph@4.4.1

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Cherry picking 4.4.1 into main
N/A

release: sourcegraph@4.4.1 (#233)

---

charts/sourcegraph/CHANGELOG.md

update changelog to include executors
CI

changelog for executors

---

charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.4.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.4.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/47256)

release: sourcegraph@4.4.2

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@4.5.0
n/a

changelog: cut sourcegraph@4.5.0

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/searcher/searcher.Service.yaml
charts/sourcegraph/templates/symbols/symbols.Service.yaml

Deployed 4.4.2 on a EKS cluster and upgraded to local branch with headless services and StatefulSets

sourcegraph: make searcher and symbols headless

---

charts/sourcegraph/CHANGELOG.md

chore: changelog update

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 4.5.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-4.5.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48151)

release: sourcegraph@4.5.1

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/values.yaml

sourcegraph: fix and remove some default values

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/templates/symbols/symbols.StatefulSet.yaml

hotfix: update symbols env

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@5.0.0
N/A

changelog: cut sourcegraph@5.0.0

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.0.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/48131)

release: sourcegraph@5.0.0

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Already released, this just makes the default head of this repo point to 5.0

release: sourcegraph@5.0.0 (#262)

---

charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

Tested changes locally and they only affect dev mode

Fix localDevMode OOMKill

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.0.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/50405)

release: sourcegraph@5.0.1

---

charts/sourcegraph/CHANGELOG.md

5.0.1 changelog

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

cherry picking release publishing PR
N/A

release: sourcegraph@5.0.1 (#268)

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Cherry picking 5.0.2 into main
---------
N/A

release: sourcegraph@5.0.2 (#272)

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.0.3 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/51302)

release: sourcegraph@5.0.3

---

charts/sourcegraph/README.md
charts/sourcegraph/examples/external-object-storage-embeddings/override.yaml
charts/sourcegraph/templates/embeddings/embeddings.Deployment.yaml
charts/sourcegraph/templates/embeddings/embeddings.Service.yaml
charts/sourcegraph/templates/embeddings/embeddings.ServiceAccount.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml
charts/sourcegraph/values.yaml

Backports changes adding Embeddings service from 
- https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/278
- https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/282
See PRs above

Add Embeddings service

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.0.4 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.4)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/52092)

release: sourcegraph@5.0.4

---

charts/sourcegraph/CHANGELOG.md

- [NA] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
Just a changelog update

update changelog for 5.0.4

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/embeddings/embeddings.Deployment.yaml

Issue: #287
Deployed locally, embeddings service starts; no helm warnings

Fix: Embeddings indentation

---

charts/sourcegraph/CHANGELOG.md

Test Plan: n/a
Part of https://github.com/sourcegraph/sourcegraph/issues/52745

update changelog for 5.0.5

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Test Plan: cherry-picked from release branch
Part of https://github.com/sourcegraph/sourcegraph/issues/52745

release: sourcegraph@5.0.5 (#292)

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/tests/defaultTagPrefix_test.yaml

Add `defaultTagPrefix` per service.
Unit tests and e2e.

add defaultTagPrefix per service

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.0.6 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.0.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/53491)

release: sourcegraph@5.0.6

---

charts/sourcegraph/CHANGELOG.md

release: cut CHANGELOG for 5.0.6

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@5.0.6 (#298)

---

charts/sourcegraph/CHANGELOG.md

n/a
---
Part of https://github.com/sourcegraph/sourcegraph/issues/49918

release: cut CHANGELOG for 5.1.0

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph/Chart.yaml

This pull request is part of the Sourcegraph 5.1.0 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/49918)

release: sourcegraph@5.1.0

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph/Chart.yaml

CI
---
Part of https://github.com/sourcegraph/sourcegraph/issues/49918

release: sourcegraph@5.1.0 (#304)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/304 did not replace all of the values, try again.
CI

release: sourcegraph@5.1.0 again

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@5.1.0 again (#307)

---

charts/sourcegraph/Chart.yaml

https://github.com/sourcegraph/deploy-sourcegraph-helm/commit/0e5d05d3cb757a5ca66edfa418631365f72a2ab9 was not released properly
follow https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/RELEASE.md
N/A

fix: make proper hotfix release

---

charts/sourcegraph/Chart.yaml

Reverts sourcegraph/deploy-sourcegraph-helm#309

Revert "fix: make proper hotfix release"

---

charts/sourcegraph/Chart.yaml

Reverts sourcegraph/deploy-sourcegraph-helm#310

Revert "Revert "fix: make proper hotfix release""

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.1 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54459)

release: sourcegraph@5.1.1

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.2 release.
* [Release batch change](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54543)

release: sourcegraph@5.1.2

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/54899)

release: sourcegraph@5.1.3

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@5.1.3 (#318)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml

Update release version for k8s executor charts for 5.1.3.

Fix release for sourcegraph executor k8s

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Release: update changelog

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/55328)

release: sourcegraph@5.1.5

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@5.1.5 (#326)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml

Update version for executors charts to 5.1.5

Update versions for executors to 5.1.5

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml

Update version files to match appVersion in charts

Update executors charts version files to 5.1.5

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

release: sourcegraph@5.1.6 (#331)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56213)

release: sourcegraph@5.1.7

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.8 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.8)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56395)

release: sourcegraph@5.1.8

---

charts/sourcegraph/CHANGELOG.md

5.1.8 - Update CHANGELOG.md

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

release: sourcegraph@5.1.8 (#344)

---

charts/sourcegraph-executor/README.md

(n/a)
previewed locally (updated link)

Fixed dead link to point to relevant sourcegraph docs

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.1.9 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.1.9)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56794)

release: sourcegraph@5.1.9

---

charts/sourcegraph/CHANGELOG.md

Part of https://github.com/sourcegraph/sourcegraph/issues/56794
🤞

release: cut changelog for 5.1.9

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

release: sourcegraph@5.1.9 (#350)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/subchart/Chart.yaml

This pull request is part of the Sourcegraph 5.2.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/56907)

release: sourcegraph@5.2.0

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/subchart/Chart.yaml

Part of https://github.com/sourcegraph/sourcegraph/issues/56907
CI

release: sourcegraph@5.2.0 (#356)

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@5.2.0
N/A

changelog: cut sourcegraph@5.2.0

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Update image tags for `5.2.0` release
`helm lint` and locally deployed successfully

fix: update images tags for 5.2.0

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

fix: update images tags for 5.2.0 (#359)

---

dev/README.md

Quick start for local dev
No test plan needed

Add quick dev instructions

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/subchart/Chart.yaml

This pull request is part of the Sourcegraph 5.2.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/57319)

release: sourcegraph@5.2.1

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/subchart/Chart.yaml

Test Plan: n/a
Part of https://github.com/sourcegraph/sourcegraph/issues/57319

5.2.1 release and changelog

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

fix image tag for 5.2.1

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.2.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58049)

release: sourcegraph@5.2.2

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

Updates the changelog for the 5.2.2 release.
N/A

Release: update changelog and cherrypick release commit

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/subchart/Chart.yaml

This pull request is part of the Sourcegraph 5.2.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58310)

release: sourcegraph@5.2.3

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

fix for 5.2.3 release

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

fix for 5.2.3 release (#373)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

release: sourcegraph@5.2.4 (#377)

---

charts/sourcegraph/CHANGELOG.md

5.2.4 changelog update

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.2.5 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.5)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/58967)

release: sourcegraph@5.2.5

---

charts/sourcegraph/CHANGELOG.md

update changelog 5.2.5

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.2.6 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.6)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59481)

release: sourcegraph@5.2.6

---

charts/sourcegraph/CHANGELOG.md

release 5.2.6 changelog

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

cherry-pick release: sourcegraph@5.2.6 (#392)

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

{"version":"5.3.666","inputs":"server=v5.3.666","type":"patch"}

PRETEND PROMOTE RELEASE - release: build 5.3.666

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)

release: sourcegraph@5.2.7

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

release: sourcegraph@5.2.7 (#408)

---

.buildkite/pipeline.yaml
charts/sourcegraph/tests/defaultTagPrefix_test.yaml
release.yaml

release from `sg-rfc relesae create --type minor`:
- https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/391
Closes https://github.com/sourcegraph/sourcegraph/issues/59064
Tested locally

rfc-795: add release manifest

---

charts/sourcegraph/CHANGELOG.md

changelog: cut sourcegraph@5.3.0
N/A

changelog: cut sourcegraph@5.3.0

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/values.yaml

Use script from https://github.com/sourcegraph/sourcegraph/pull/60365
CI

Leverage readiness script

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/values.yaml

Reverts sourcegraph/deploy-sourcegraph-helm#420
We leverage this repo for Cloud and current images do not have this script
Revert, no review required

Revert "Leverage readiness script"

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)

release: sourcegraph@5.3.0

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.3.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60691)

release: sourcegraph@5.3.1

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

release: sourcegraph@5.3.1 (#427)

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.3.2 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.2)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60972)

release: sourcegraph@5.3.2

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

Release: cherry pick 5.3.2 release commit

---

.buildkite/pipeline.yaml
release.yaml

plugin was tested over https://github.com/sourcegraph/deploy-sourcegraph-k8s/pull/102
CI

chg/rel: use default sg

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

This pull request is part of the Sourcegraph 5.3.3 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.3)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/61302)

release: sourcegraph@5.3.3

---

release.yaml

- **build: add missing " to git command**
Tested during release

Fix release.yaml missing "

---

.github/workflows/gcs_chart_publish_release.yml

release: update helm publish action

---

release.yaml

* Use `wget` instead of `curl`
* Add `wget` to requirements list
* Validate before promoting to release registry
Manual testing

release: more udpate to release config

---

.github/workflows/release-amis.yml

Moves AMI automation from monorepo to this repo. Directly related to https://github.com/sourcegraph/sourcegraph/pull/62975
Will run manually

chores(ci): add ami automation

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/jaeger/jaeger-collector.Service.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/otel-collector/otel-collector.Deployment.yaml
charts/sourcegraph/values.yaml

fix/otel-jaeger: update jaeger deployment

---

charts/sourcegraph-appliance/templates/deployment.yaml

Enable self-update background loop by default.
https://linear.app/sourcegraph/issue/REL-212/appliance-can-self-upgrade
Ran `helm template` against the chart.

feat(appliance): add deployment name env var

---

charts/sourcegraph-appliance/templates/ingress.yaml
charts/sourcegraph-appliance/templates/service.yaml

> [!NOTE]  
> This is part of a stack of PRs created using [git-machete](https://github.com/VirtusLab/git-machete)
> This is my first time using it
> This stack includes:
> #494 - Add Namespace
> #495 - Maintaince UI 
> #496 - Appliance Ingress <- You are here
> #497 - Appliance Selfupdater
This PR depends on https://github.com/sourcegraph/sourcegraph/pull/63627
Manual testing

feat(appliance): Add Ingress and Service

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/templates/deployment.yaml
charts/sourcegraph-appliance/values.yaml

appliance: expose APPLIANCE_NO_RESOURCE_RESTRICTIONS

---

README.md

Previous link seems to be dead
- N/A

Update link to Helm quickstart

---

charts/sourcegraph-appliance/Chart.yaml

Change the chart name and match the version.

Update name and version

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

release: cherrypick 5.6.185 release

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

(promote) release: build v5.6.2535

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

(promote) release: build v5.7.0

---

.github/workflows/backport.yml

standardizing across deploy-* repos
NA

feat/ci: add backport GHA

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

(promote) release: build v5.7.2474

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Release update images

---

charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml

improving documentation for JSON object examples in helm configuration

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

(promote) release: build v5.8.0

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

update release tags for 5.8.1579

---

charts/sourcegraph/README.md
charts/sourcegraph/README.md.gotmpl

This link being broken was brought to my attention :) 
N/A

Fix deadlink in README

---

charts/sourcegraph/templates/NOTES.txt

I only updated a link in the docs, so I skipped the checklist and testing below.
No testing, because this only changes a text string

fix: update link to new docs page

---

charts/sourcegraph-appliance/Chart.yaml
charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml
charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

(promote) release: build v5.9.1590

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Update Postgres 12 images to Postgres 16.
CI tests

chore(rel): update postgres images to 16 versions

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Fix image tags that got missed by tooling
Manually tested/ CI

fix(rel): fix db image tags 5.10.0 release

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

(promote) release: build v5.10.2832

---

charts/sourcegraph/examples/jaeger/override.yaml

Create Jaeger override to apply easily

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/examples/subchart/Chart.yaml
charts/sourcegraph/values.yaml

(promote) release: build v5.11.0

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Other one had too many conflicts
CI

Release: 5.11.3601 

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Update docker images to latest Sourcegraph release
CI

chore(rel): update latest tags

---

charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

(promote) release: build v6.3.4167

---

scripts/ci/install-helm-env.sh

Update Helm install script for CI testing pipeline.
CI

fix(rel): update helm install script
