sourcegraph/deploy-sourcegraph-helm

sourcegraph/templates/_tracing.tpl
sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml
sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml
sourcegraph/templates/grafana/grafana.StatefulSet.yaml
sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
sourcegraph/templates/jaeger/jaeger.Deployment.yaml
sourcegraph/templates/minio/minio.Deployment.yaml
sourcegraph/templates/pgsql/pgsql.Deployment.yaml
sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
sourcegraph/templates/prometheus/prometheus.Deployment.yaml
sourcegraph/templates/query-runner/query-runner.Deployment.yaml
sourcegraph/templates/redis/redis-cache.Deployment.yaml
sourcegraph/templates/redis/redis-store.Deployment.yaml
sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
sourcegraph/templates/searcher/searcher.Deployment.yaml
sourcegraph/templates/symbols/symbols.Deployment.yaml
sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
sourcegraph/templates/worker/worker.Deployment.yaml
sourcegraph/values.yaml

Environment variables for all deployables can now be customized using a map. Values can be overridden from a separate file like this:
```
pgsql:
env:
PGHOST:
value: something_else // use a custom value instead of the default provided in values.yaml
PGDATABASE:
valueFrom:  // replace default value with a secret key ref
secretKeyRef:
name: pgsql-secret
key: database
CODEINTEL_PGSSLMODE: null // unset this variable entirely, it will not be included in the env list
NEW_VARIABLE:
value: "something new" // add a custom variable
```
The result will include all the default values merged with the modifications from the override file.
Two downsides to this implementation:
- Ordering is not preserved (env var's will be alphabetically sorted instead of insertion sorted)
- No templating is allowed - …

Allow customization of environment variables

---

sourcegraph/templates/frontend/sourcegraph-frontend.Role.yaml
sourcegraph/templates/frontend/sourcegraph-frontend.RoleBinding.yaml
sourcegraph/templates/prometheus/prometheus.ClusterRole.yaml
sourcegraph/templates/prometheus/prometheus.ConfigMap.yaml
sourcegraph/templates/prometheus/prometheus.RoleBinding.yaml
sourcegraph/values.yaml

Matches the changes for frontend and prometheus from the https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph/-/tree/overlays/non-privileged overlay. Prometheus and Frontend bind to a pre-existing clusterrole view instead of creating their own role.
Not enabled by default.

Support running SG without create role permissions

---

sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
sourcegraph/values.yaml

indexedSearch is unusual because it combines both zoekt-webserver and indexserver, each with separate images, resources and security contexts. Since they're deployed together, I wanted to keep the configuration relatively close as well.
An alternative approach would be to make both the searcher and indexer a subconfiguration of indexedSearch, i.e.:
```
indexedSearch:
indexer:
image: <zoekt-indexserver>
etc etc
searcher:
image: <zoekt-webserver>
etc etc
```
I chose not to take that approach and instead keep both as a top-level configuration because it makes the structure more consistent. The consistency make it easier to automate changes such as updating the image references.

Rename searchIndexer to indexedSearchIndexer to keep configuration alongside indexedSearch

---

sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml

Make it easier to use an SSH key for credentials in gitserver by automatically generating the correct volume refs / mounts when `gitserver.sshSecret` is provided (The secret must exist already - we don't generate it). Follows the pattern documented in https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph@a3e354cb4542794683c6df1ee154972b6f08543a/-/blob/base/gitserver/gitserver.StatefulSet.yaml?L89.
Note - there's a little bit of confusion about what file permissions are needed, documented in https://github.com/sourcegraph/sourcegraph/issues/29117. I erred on the side of more permissions in the meantime.

Add configuration for mounting ssh secret in gitserver

---

sourcegraph/templates/_helpers.tpl
sourcegraph/templates/_tracing.tpl
sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
sourcegraph/templates/jaeger/jaeger.Deployment.yaml
sourcegraph/templates/pgsql/pgsql.Deployment.yaml
sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
sourcegraph/templates/redis/redis-cache.Deployment.yaml
sourcegraph/templates/redis/redis-store.Deployment.yaml
sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
sourcegraph/values.yaml

Previously, the name of docker images was inferred from the values.yaml key value, and occasionally explicitly set in the deployment template. It could also be overridden by specifying a name in the values.yaml. 
Now the docker image name must be specified in the values.yaml alongside the tag. This makes it possible to write tooling to fetch and update the docker image name, and simplifies the naming logic.

Move docker image specification to values.yaml

---

sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

Frontend pods try to write the site-config.json to /home/sourcegraph, but fail because we're forcing a read-only root file system.
I confirmed that the instructions to use a configmap for the site config still work with this change (https://docs.sourcegraph.com/admin/config/advanced_config_file)

Mount home directory as an emptyDir for frontend

---

.github/workflows/chart_publish.yml

Uses https://github.com/marketplace/actions/helm-chart-releaser to auto-publish the helm chart to a Github page (https://sourcegraph.github.io/deploy-sourcegraph-helm/). Right now it will publish any commit on main to the releases page, but we can make it dependent on checks passing (like those added in https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/23).

Add Github Action to publish chart versions

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/templates/cadvisor/cadvisor.PodSecurityPolicy.yaml
charts/sourcegraph/values.yaml

Allow cadvisor PSP resource to be toggled off. PSP's are deprecated as of Kubernetes 1.21 and will be fully removed in Kubernetes 1.25.
It's not terribly urgent to make this change but I'm using this opportunity to test the publish pipeline.

Add toggle for cadvisor podSecurityPolicy resource

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml
charts/sourcegraph/values.yaml

The postgres exporter for the pgsql deployment was not configured correctly - now the env specification matches codeintel-db, as intended, and monitoring is working.

Fix postgres monitoring for pgsql

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.ServiceAccount.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml
charts/sourcegraph/templates/grafana/grafana.ServiceAccount.yaml
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/minio/minio.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/templates/searcher/searcher.Deployment.yaml
charts/sourcegraph/templates/symbols/symbols.Deployment.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml

Credentials are defined for Deployments and StatefulSets as `spec.template.spec.imagePullSecrets`, not `spec.imagePullSecrets`. Some deployments were missing the definition entirely, and others were at the correct level but the location is now standardized.

Fix templates for imagePullSecrets configuration

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/extra-volumes/override.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/templates/searcher/searcher.Deployment.yaml
charts/sourcegraph/templates/symbols/symbols.Deployment.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml

The searcher deployment relies on having a writable `/tmp` directory. Since we run by default with a read-only root file system, structural searches fail to run without this directory.
While adding the /tmp mount, I noticed that the optional volume configuration was missing on many deployments, so I fixed that as well.

Add mandatory /tmp dir to searcher deployment, fix missing volume configuration

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/values.yaml

No significant changes for this release, version bump only

Default to latest Sourcegraph release (3.36.2)

---

charts/sourcegraph/Chart.yaml
charts/sourcegraph/values.yaml

```sh
sg ops update-images -kind helm -pin-tag 3.36.3 charts/sourcegraph/.
```

Default to latest Sourcegraph release (3.36.3)

---

charts/sourcegraph/values.yaml

before the change running `helm template`
```
coalesce.go:220: warning: cannot overwrite table with non table for sourcegraph.sourcegraph.tolerations (map[])
```
After the change, it's no longer there.

Fix default global tolerations value

---

charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/minio/minio.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/templates/searcher/searcher.Deployment.yaml
charts/sourcegraph/templates/symbols/symbols.Deployment.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml

This PR introduces three partial templates for `tolerations`, `affinity`, and `nodeSelector`.
Usage
> `trim` may seem weird, but this is the only way to avoid introducing the extra `\n` which is bugging me a lot...
```yaml
{{- include "sourcegraph.nodeSelector" (list . "serviceName" ) | trim | nindent 6 }}
{{- include "sourcegraph.affinity" (list . "serviceName" ) | trim | nindent 6 }}
{{- include "sourcegraph.tolerations" (list . "serviceName" ) | trim | nindent 6 }}
```
Most changes are just copying & pasting, but please help me double-check!
not blocking
- maybe we should include them explicitly in `values.yaml`? Related ->  https://github.com/sourcegraph/sourcegraph/issues/31016
`override.yaml`
```
sourcegraph:
nodeSelector:
node-type: memory-optimized
tolerations:
- key: node-type …
```

Add per-service scheduling config support

---

charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/values.yaml

close https://github.com/sourcegraph/sourcegraph/issues/31257
Not blocking 3.37 release
I don't have good experience working with helm hook in the past and often yield unexpected result. For example, the `helm install/update` will just fail when the cluster fails to schedule pods, or `pgsql` is not ready yet.
On the other hand, we can run the `Job` with `post-install` and `post-upgrade` hooks. Maybe it can help increase visibility when there's a failing migration?

Add migrator initContainers to frontend

---

charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/minio/minio.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/templates/searcher/searcher.Deployment.yaml
charts/sourcegraph/templates/symbols/symbols.Deployment.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml

close https://github.com/sourcegraph/sourcegraph/issues/29063
Install a release from the previous commit,
```bash
git checkout HEAD~
helm install -n sourcegraph -f charts/sourcegraph/override.yaml sourcegraph charts/sourcegraph/.
```
Checkout back to the current branch and run `helm diff`, you should see no breaking change
```bash
git checkout 02-22-Support_container_args_override
helm diff -n sourcegraph -f charts/sourcegraph/override.yaml sourcegraph charts/sourcegraph/.
```

Support container args override

---

charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/_tracing.tpl
charts/sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Deployment.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/minio/minio.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/templates/searcher/searcher.Deployment.yaml
charts/sourcegraph/templates/symbols/symbols.Deployment.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.Deployment.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml
charts/sourcegraph/values.yaml

We're currently using and
- `podSecurityContext` as container-level `securityContext` (the naming is misleading)
- `securityContext` as pod-level `securityContext` (okay, but we should be more explicit)
This PR
- renamed `podSecurityContext` to `containerSecurityContext`
- renamed `securityContext` to `podSecurityContext`
The test plan is to `diff` the output of rendered manifest, no change is expected.
```sh
kind create cluster
```
Revert to `main`
```sh
git checkout HEAD~
```
```sh
helm upgrade --install -n sourcegraph --set storageClass.create=false,storageClass.name=standard,sourcegraph.localDevMode=true sourcegraph charts/sourcegraph/.
```
```sh
git checkout 02-25-Fix_securityContext_values_name
```
```sh
helm diff -n sourcegraph --set …
```

Fix securityContext values name

---

charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Deployment.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Deployment.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml

current a lot of images are missing imagePullPolicy. Search through all the yaml files that had `images: ` and add the missing `imagePullPolicy: ` 
Inspect the rendered template
```sh
helm template .
```
close https://github.com/sourcegraph/sourcegraph/issues/31887

Add missing imagePullPolicy 

---

charts/sourcegraph/examples/advanced-scheduling/override.yaml
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/tests/affinity_test.yaml

This PR added an example override to show advanced scheduling
Also added `tpl` support to affinity rule, so string template can be evaluated as template during rendering
`override.yaml`
```
labels:
app.kubernetes.io/name: '{{ include "sourcegraph.name" . }}'
app.kubernetes.io/instance: '{{ .Release.Name }}'
```
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/280065f45e5738f1a1deed61b235192d1e5893c4/charts/sourcegraph/templates/_helpers.tpl#L75-L86
```sh
helm template -f ./charts/sourcegraph/examples/advanced-scheduling/override.yaml sourcegraph charts/sourcegraph/.
```
close https://github.com/sourcegraph/sourcegraph/issues/31875

Add advanced scheduling example override

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md.gotmpl

I backfilled our changelog with commits that I think it's worth mentioning ` git log --oneline -- charts/sourcegraph/`
N/A, new release

sourcegraph: release 0.4.0

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/minio/minio.Deployment.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.Deployment.yaml
charts/sourcegraph/values.yaml

- repo-updater
It's loud and clear that repo-updater is not horizontally scalable https://github.com/sourcegraph/sourcegraph/tree/main/cmd/repo-updater 
- ~syntect-server~
~Waiting for confirmation on syntech-server https://sourcegraph.slack.com/archives/CHXHX7XAS/p1646783148867999~
syntect-server is horizontally scable.
- minio
`minio` supports HA, but not the way how we run it nowadays
`.spec.replicas` of repo-updater and syntech-server deployment should be unchanged
```sh
helm template --set repoUpdater.replicaCount=10,syntechServer.replicaCount=10 charts/sourcegraph/. | yq e '. | select(.kind == "Deployment" and (.metadata.name == "repo-updater" or .metadata.name == "syntect-server"))'
```
close https://github.com/sourcegraph/sourcegraph/issues/32095

Remove replicaCount values of unscalable services

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
charts/sourcegraph/values.yaml

[github-proxy](https://github.com/sourcegraph/sourcegraph/tree/main/cmd/github-proxy) is a singleton service
why?
- https://github.com/sourcegraph/sourcegraph/tree/main/cmd/github-proxy
- https://docs.sourcegraph.com/dev/background-information/architecture, it's a rectangle not a box
- it tracks requests in memory, so yeah, you really shouldn't scale it up
Replicas should stay `1`.
```sh
helm template --set githubProxy.replicaCount=10 charts/sourcegraph/. | yq e '. | select(.kind == "Deployment" and .metadata.name == "github-proxy")'
```

Remove replicaCount values for github-proxy

---

charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/jaeger/jaeger-collector.Service.yaml
charts/sourcegraph/templates/jaeger/jaeger-query.Service.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml

We were rendering duplicated labels `app.kubernetes.io/component` and `app.kubernetes.io/name` in jaeger `deploy` and `svc`. This is causing problems when piping rendered output to `kustomize`. 
```
stomize-chart/kustomize. error output:
Error: received error yaml: unmarshal errors:
line 29: mapping key "app.kubernetes.io/name" already defined at line 27 for the following resource:
```
This PR 
- cleans up all these duplicated labels.
- enforce consistency to some extent without introducing any breaking change
- use `app.kubernetes.io/component: all-in-one` and `app.kubernetes.io/name: jaeger` as much as possible. They are the value of `matchLabels` right now and we can't change them, so we might as well use them as the standard for all jaeger components.
See below comment for the latest …

Fix jaeger labels selector

---

charts/sourcegraph/examples/kustomize-chart/README.md
charts/sourcegraph/examples/kustomize-chart/kustomization.yaml
charts/sourcegraph/examples/kustomize-chart/kustomize
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/jaeger/jaeger-collector.Service.yaml
charts/sourcegraph/templates/jaeger/jaeger-query.Service.yaml
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml

This PR added example to integrate kustomize into `helm install`
Why not `helm-x`? I just realize the project was abandoned and doesn't work with helm v3. Its core functionality was extracted into another library https://github.com/variantdev/chartify. 
See added README.md
close https://github.com/sourcegraph/sourcegraph/issues/32178

Add docs to kustomize chart

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/storageclass.yaml
charts/sourcegraph/tests/storageClass_test.yaml

Rendered manifest had broken indentation when `storageClass.parameters` is not empty
```
Error: Error: YAML parse error on sourcegraph/templates/storageclass.yaml: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
```
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name:  standard
labels:
helm.sh/chart: sourcegraph-0.5.0
app.kubernetes.io/name: sourcegraph
app.kubernetes.io/instance: sourcegraph
app.kubernetes.io/version: "3.37.0"
app.kubernetes.io/managed-by: Helm
deploy: sourcegraph-storage
annotations:
provisioner: kubernetes.io/gce-pd
parameters:
type: pd-ssd
zones: us-central1-f
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
See added unit test

Fix broken indentation in storageClass params

---

charts/sourcegraph/templates/_tracing.tpl

The `{{- end }}` was misplaced in the partial template.
When `tracingAgent` is disabled, it will leave a dangling `securityContext:` in the rendered manifests. Tracing is always enabled by default, so we missed it
Run `helm template` with `tracingAgent.enabled=false`, the rendered manifest should look good

Fix tracing partial template

---

charts/sourcegraph/README.md
charts/sourcegraph/README.md.gotmpl

Followup from the UX of https://github.com/sourcegraph/sourcegraph/issues/27759: using the `--wait` flag makes the install wait for the resources to become healthy.
README should look nice

Recommend use of the wait command, improve formatting

---

charts/sourcegraph/values.yaml

Enable tracking of helm chart usage by using the deploy_type env var.
Compared diffs before and after - new env var is set. Frontend will crash unless the changes from https://github.com/sourcegraph/sourcegraph/pull/32407 are present.

Set deploy_type env var to track helm chart usage

---

charts/sourcegraph/README.md
charts/sourcegraph/examples/tune-internal-databases/override.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.ConfigMap.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.ConfigMap.yaml
charts/sourcegraph/templates/pgsql/pgsql.ConfigMap.yaml
charts/sourcegraph/tests/codeInsightsDBAdditionalConfig_test.yaml
charts/sourcegraph/tests/codeIntelDBAdditionalConfig_test.yaml
charts/sourcegraph/tests/pgsqlAdditionalConfig_test.yaml
charts/sourcegraph/tests/postgresAdditionalConfig_test.yaml
charts/sourcegraph/values.yaml

We can now extend existing postgres configmap instead of requiring maintaining a fork of it
See added unit tests for template testing and sanity check
To check it actually works
```yaml
storageClass:
create: false
name: standard
reclaimPolicy: Delete
sourcegraph: 
localDevMode: true
pgsql:
additionalConfig: |
max_connections = 500
```
Deploy the chart
```sh
kind create cluster
helm upgrade --install -n sourcegraph -f ./override.yaml sourcegraph charts/sourcegraph/.
```
```sh
kubectl exec pgsql-0 -- psql postgres://sg@localhost -c 'show max_connections;'
```
you should see
```
max_connections
-----------------
500
(1 row)
```
The default is
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/646b48eb80456c53a97b83121322c130680847cf/charts/sourcegraph/templates/pgsql/pgsql.ConfigMap. …

Support extending postgres server conf

---

charts/sourcegraph/examples/gcp/override.yaml

The example given for GCP did not actually create a load balancer. According to [the docs](https://cloud.google.com/kubernetes-engine/docs/how-to/custom-ingress-controller#controller_summary), GKE relies on the `kubernetes.io/ingress.class` annotation. If that annotation is not set but ingressClassName is, no load balancer is provisioned.
Supposedly you're able to specify both `kubernetes.io/ingress.class` and `ingressClassName`, but in practice I got an error when trying to provide both, so I removed it.
I'll update the example in the main docs as well, but there's an open PR + a couple other changes we might want to make before then.
Install the chart, confirm a load balancer gets created.

Fix ingress settings on GCP example

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.ConfigMap.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Service.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.StatefulSet.yaml
charts/sourcegraph/values.yaml

Migrates Code Insights to use a Postgres base image.
**Q**: This change won't work without an image update (https://github.com/sourcegraph/sourcegraph/pull/32616). We don't normally update image references until a release, but this is actually a backwards compatible change with the 3.37 release Should I update the image ref and merge, or label this as a release-blocker instead?
Tested both a clean install and an upgrade - no issues. This is basically the same change as https://github.com/sourcegraph/deploy-sourcegraph/pull/4099.
Diff on the template looks correct:
```diff
50c50
<     description: Configuration for TimescaleDB
---
>     description: Configuration for Code Insights
57,63d56
<     # --------------------------------------------------------------------------
<     # IMPORTANT: …
```

Migrate Code Insights db to postgres, add exporter

---

charts/sourcegraph/templates/frontend/sourcegraph-frontend.Ingress.yaml

Testing https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/89 I realized that the ingress logic was slightly incomplete. Now we only render the tls section when both variables are provided.
Rendering looks ok, we can now provide host value only if it's really important.

Only render tls section on frontend ingress if both variables provided

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/minio/minio.Deployment.yaml
charts/sourcegraph/templates/minio/minio.Secret.yaml
charts/sourcegraph/templates/precise-code-intel/worker.Deployment.yaml
charts/sourcegraph/tests/affinity_test.yaml
charts/sourcegraph/tests/localDevMode_test.yaml
charts/sourcegraph/tests/minioAuth_test.yaml
charts/sourcegraph/values.yaml

Prototype to demonstrate providing an interface for minio credentials that allows us to generate or reuse an existing Secret resource instead of use direct env vars. I haven't fully tested this approach since it's still in the proof-of-concept phase.
**Decisions / consequences:**
- This implementation is opinionated about the structure of the minio-auth Secret, which simplifies the logic and allows us to easily reference the credentials in other deployments. Customers who want to use a different structure can use kustomize to alter the configuration.
- We're not randomly generating values for the credentials to preserve compatibility with the helm template command (we're stuck with either generating a new value every time helm runs, or requiring access to the existing secret).
- I went …

Switch minio to use a secret for credentials, replace deprecated env vars

---

.github/workflows/chart_publish.yml

Switch to publishing from a release branch instead of main. ~~The name standard is up for debate! Alternatively, we could publish from tags?~~
After discussion, we're happy with the release branch name convention. Tags will be created by the chart publisher.
Charts are only published from release branches

Publish chart on release branches instead of main

---

.buildkite/pipeline.yaml

Rename buildkite queue to standard
No review required: ci queue hanges
[_Created by Sourcegraph batch change `sourcegraph/update-to-stateless-queue`._](https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/update-to-stateless-queue)

Rename buildkite queue from `job` to `standard`

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Secret.yaml
charts/sourcegraph/templates/pgsql/pgsql.StatefulSet.yaml
charts/sourcegraph/tests/affinity_test.yaml
charts/sourcegraph/tests/localDevMode_test.yaml
charts/sourcegraph/tests/pgsqlAuth_test.yaml
charts/sourcegraph/values.yaml

Similar to https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/85, but for database credentials.
Prototype to demonstrate providing an interface for database credentials that allows us to generate or reuse an existing Secret resource instead of use direct env vars. This isn't a full implementation (missing codeintel / codeinsights) since it's still a proof of concept. The migrator chart would also need to be updated.
Decisions / consequences:
* Just like the minio implementation, this is opinionated about the structure for the Secret. Is this riskier with auth for an external database?
* This approach vastly simplifies the management of database credentials - they're specified in one location now, instead of 4 different places.
* The variable names are all over the place (example: …

Use secrets for pgsql credentials

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Secret.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.StatefulSet.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Secret.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Service.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.StatefulSet.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml
charts/sourcegraph/templates/pgsql/pgsql.Secret.yaml
charts/sourcegraph/tests/affinity_test.yaml
charts/sourcegraph/tests/localDevMode_test.yaml
charts/sourcegraph/values.yaml

Same as https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/86, but for codeintel / codeinsights.
**Note**: customizing the database name for codeinsights doesn't work with the 3.38 images, but it will work with 3.39 when we swap over to the pgsql docker container.
There will be a separate PR to update the migrator chart.
Tested with default values, custom values for all, and providing a secret. Upgrade from previous version worked without a problem.

Convert codeintel-db and codeinsights-db to use secrets for credentials

---

charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/README.md.gotmpl
charts/sourcegraph-migrator/templates/_helpers.tpl
charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml
charts/sourcegraph-migrator/values.yaml

Updates the migrator chart to use the same secret references as #86, #98.
Rendered manifest matches the migrator structure from the parent chart.

Update migrator chart to reference database secrets

---

charts/sourcegraph/templates/NOTES.txt
charts/sourcegraph/tests/prometheusPrivileged_test.yaml

close https://github.com/sourcegraph/sourcegraph/issues/32852
```sh
helm upgrade --dry-run --install -n sourcegraph --create-namespace --set prometheus.privileged=false sourcegraph charts/sourcegraph/
```
you should see
```
NOTES:
Thank you for installing sourcegraph.
Your release is named sourcegraph.
To learn more about supported configuration, check out https://docs.sourcegraph.com/admin/install/kubernetes/helm.
🚧 Warning 🚧
You have set 'prometheus.privileged' to 'false'. As a result, our built-in observability stack will not function properly.
Please assign proper permission to Service Account 'prometheus'.
You can do so by creating the proper ClusterRole and ClusterRoleBinding.
You may consult https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/template …
```

Add warning when prometheus is running in non-privileged mode

---

charts/sourcegraph/templates/codeinsights-db/codeinsights-db.StatefulSet.yaml

Adds the same initContainer from https://github.com/sourcegraph/deploy-sourcegraph/pull/4115 to codeinsights-db. This doesn't seem necessary for pure helm installs but should reduce friction when migrating from kustomize.
Upgraded from previous version to current version.

Add initContainer to codeinsights-db

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.StatefulSet.yaml
charts/sourcegraph/values.yaml

Enable exporter on code insights. Won't actually collect metrics until the 3.39 release switches the codeinsights db to postgres.
Confirmed metrics are ingested on Grafana dashboard

Add pgsql exporter to codeinsights

---

.github/workflows/gcs_chart_publish_insiders.yml
.github/workflows/gcs_chart_publish_release.yml

By default, helm-gcs uses `gs://<bucket name>` as the public URL for the index.yaml, and downloading the chart requires installing the helm-gcs plugin.
To avoid adding this dependency (and actually use Cloudflare), configure the https public url during pushes.
helm chart install succeeds without the helm-gcs plugin.

Set public url when pushing to GCS

---

.github/workflows/gcs_chart_publish_insiders.yml

The release batch change added quotes around the chart version, so the sed used for insiders releases no longer works.
Probably this could be done in a more elegant / graceful way but adding the quotes is pretty easy to unblock us for now.
Chart publish should work this time

Add quotes to chart version replacement

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/NOTES.txt
charts/sourcegraph/templates/cadvisor/cadvisor.DaemonSet.yaml
charts/sourcegraph/tests/cadvisorPrivileged_test.yaml
charts/sourcegraph/values.yaml

Follow up https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/804
tested on a live gke cluster
deploy sourcegraph as usual
deploy a stress test pod
```sh
apiVersion: v1
kind: Pod
metadata:
name: stress
namespace: sourcegraph
spec:
containers:
- name: stress
image: progrium/stress
command:
- sleep
- infinity
resources:
requests:
memory: 100Mi
limits:
memory: 128Mi
```
exec into the pod and run
```sh
stress --cpu 1 --vm-bytes 300M --timeout 10s
```
oom events show up as expected

fix: cadvisor can pickup oom events

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

The alpine-3.12 image was removed in https://github.com/sourcegraph/sourcegraph/pull/34906 (as a followup to https://github.com/sourcegraph/sourcegraph/pull/34508). We directly reference the alpine-3.12 image here to run init commands, so the reference needs to be updated.
Note: the insiders reference will be updated as part of the next release.
Not tested directly apart from verifying the image reference - however, the same change has already been made in https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4336 and has been working fine.

Update alpine-3.12 references

---

charts/sourcegraph/templates/storageclass.yaml
charts/sourcegraph/tests/storageClass_test.yaml

We ask customer to unset `storageClass.type=null` when using AKS, but this breaks the template https://sourcegraph.slack.com/archives/C02E4HE42BX/p1655238677152839
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name:  sourcegraph
labels:
helm.sh/chart: sourcegraph-3.40.1
app.kubernetes.io/name: sourcegraph
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "3.40.1"
app.kubernetes.io/managed-by: Helm
deploy: sourcegraph-storage
annotations:
provisioner: disk.csi.azure.com
parameters:
type:
storageaccounttype: Premium_LRS
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```
This PR prevent the rendering of `type: <>` completely
we should probably run `kubeval` on all example overrides
```sh
helm template --values …
```

Fix storage class `type` parameter

---

charts/sourcegraph/templates/symbols/symbols.Deployment.yaml

Because the `symbols` container's processes run as user 100 (`sourcegraph`):
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/b6d554e3f594b9c43951f84520f174fae29114ab/charts/sourcegraph/values.yaml#L997
ctags doesn't have write permission to `/tmp`.
Tested in https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/4594

Give ctags a writable temp dir

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.StatefulSet.yaml
charts/sourcegraph/values.yaml

The codeinsights-db data volumes mount at a different path than pgsql / codeintel-db. The initContainer was pointed at the wrong path, so the file permission adjustment was unable to run.
There is also a problem with the initContainer permissions - the securityContext settings are shared between all alpine images, but the user associated with pgsql / codeintel-db is different. As a quick fix I've added an override for codeinsights, but we'll want to roll this change out everywhere.
Confirmed initContainer actually changes file permissions after this change

Fix mount path used by codeinsights-db initContainer

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/examples/envoy/README.md
charts/sourcegraph/examples/envoy/override.yaml

Helm version of https://github.com/sourcegraph/deploy-sourcegraph/pull/4150
This PR adds a new envoy filter overlay as an example to resolve the following error for instances that are running service mesh (ex. istio):
```
Strconv.Atoi: parsing "": invalid syntax
```
This error occurs when the service mesh like istio drops trailers for http1 by default. Enable trailers using this overlay resolves the issue.
Tested on a minikube instance

Add envoy filter override

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/README.md.gotmpl
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/cadvisor/cadvisor.ServiceAccount.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.ServiceAccount.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.ServiceAccount.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.ServiceAccount.yaml
charts/sourcegraph/templates/github-proxy/github-proxy.ServiceAccount.yaml
charts/sourcegraph/templates/gitserver/gitserver.ServiceAccount.yaml
charts/sourcegraph/templates/grafana/grafana.ServiceAccount.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.ServiceAccount.yaml
charts/sourcegraph/templates/jaeger/jaeger.ServiceAccount.yaml
charts/sourcegraph/templates/minio/minio.ServiceAccount.yaml
charts/sourcegraph/templates/pgsql/pgsql.ServiceAccount.yaml
charts/sourcegraph/templates/precise-code-intel/worker.ServiceAccount.yaml
charts/sourcegraph/templates/prometheus/prometheus.ServiceAccount.yaml
charts/sourcegraph/templates/redis/redis-cache.ServiceAccount.yaml
charts/sourcegraph/templates/repo-updater/repo-updater.ServiceAccount.yaml
charts/sourcegraph/templates/searcher/searcher.ServiceAccount.yaml
charts/sourcegraph/templates/symbols/symbols.ServiceAccount.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.ServiceAccount.yaml
charts/sourcegraph/templates/worker/worker.ServiceAccount.yaml
charts/sourcegraph/tests/serviceAccountAnnotations_test.yaml

In Cloud, we need to annotate the Kubernetes service account in order to impersonate as a GCP service account
unit test
or run
`override.yaml`
```yaml
frontend:
serviceAccount:
annotations:
iam.gke.io/gcp-service-account: sourcegraph@sourcegraph.iam.gserviceaccount.com
```
```sh
helm template -f ./override.yaml sourcegraph charts/sourcegraph/.
```

Add support to set service account annotations

---

charts/sourcegraph/templates/worker/worker-executors.Service.yaml
charts/sourcegraph/templates/worker/worker.Deployment.yaml

This adds a scrape config for a new port exposed by the worker service that serves the collected executor metrics.
Will have to test it once https://github.com/sourcegraph/sourcegraph/pull/36969 landed, otherwise we'll revert.

sourcegraph: Add new worker prometheus scrape target

---

.github/workflows/helm_lint_test.yml

When no change is made to the chart, the CI will fail because it tried to install the chart without setting up the kind cluster
this change ensures these tests are only run when helm chart is changed to avoid running unnecessary test
ci should pass

ci: fix helm test

---

charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/frontend/sourcegraph-frontend-internal.Service.yaml
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Ingress.yaml
charts/sourcegraph/templates/grafana/grafana.Service.yaml
charts/sourcegraph/templates/indexed-search/indexed-search.StatefulSet.yaml
charts/sourcegraph/templates/jaeger/jaeger-collector.Service.yaml
charts/sourcegraph/templates/jaeger/jaeger-query.Service.yaml
charts/sourcegraph/templates/prometheus/prometheus.Service.yaml
charts/sourcegraph/templates/storageclass.yaml
charts/sourcegraph/templates/syntect-server/syntect-server.Service.yaml

A [customer reported lint warnings](https://sourcegraph.slack.com/archives/C03SBTYH3S9/p1661186892313959?thread_ts=1659985666.766349&cid=C03SBTYH3S9) in the output yaml from kube yaml plugin for IntellilJ because `annotation:` keys were set with no value.
This PR updates the chart to not emit the annotations key if no values are going to be set.
I am not sure how to enforce this in unit tests. `helm unittest` seems to only be capable of checking values, not the existence of keys, so tests can't tell the difference between the `annotations:` key not being present or simply empty.
Alternatively, we could just require that every entity has a description annotation.
Ran `helm template ./charts/sourcegraph` and ensured all `annotations:` keys had values.

Don't include `annotations:` key when there are no annotations

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

A customer reported issues when they tried to set `ingressClassName`:
```
Error: INSTALLATION FAILED: Ingress.extensions "sourcegraph-frontend" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```
The solution is to set `annotations.kubernetes.io/ingress.class` to `null`.
This PR updates the documentation to make this more clear.
This is just updating the documentation.

docs: set kubernetes.io/ingress.class to null if ingressClassName is set

---

charts/sourcegraph/examples/ingress/override.yaml

Fix example to follow docs added in https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/165
I ran the following two commands and looked at the diff to verify that `kubernetes.io/ingress.class` was `null`
* `helm template ./charts/sourcegraph > output.yaml`
* `helm template --values ./charts/sourcegraph/examples/ingress/override.yaml ./charts/sourcegraph > ingress.yaml`

docs: Don't set both ingress.class and ingressClassName in example

---

charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

The code backing this variable has been unused for atleast a year. Removing this also allows us to simplify deployment, since right now we tell customers to assign ephemeral storage to frontend (but that will never be used!)
Test Plan: CI. I previously did a lot of validation that we can remove this (reading code, inspecting prod and dogfood environments for cache dir usage)
Part of https://github.com/sourcegraph/sourcegraph/issues/38934

frontend: remove unused CACHE_DIR

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This value is intended to have multiple json objects within it, thereby it should be a `[]` to denote an array
CI

sourcegraph: fix `extraResources` default values

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/storageclass.yaml
charts/sourcegraph/tests/storageClass_test.yaml
charts/sourcegraph/values.yaml

context: https://sourcegraph.slack.com/archives/C03LCPCT3SP/p1664966342611049?thread_ts=1664545745.855499&cid=C03LCPCT3SP
Add option to configure https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
On cloud, adding `allowedTopologies` allow provisioning of regional PD with only one worker node present
For on-prem customer, this would be helpful if they would like to restrict where to run sourcegraph in a shared multi-zone cluster
unit test

sourcegraph: add `allowedTopologies` support to storageclass

---

TEST.md
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/NOTES.txt
charts/sourcegraph/templates/node-exporter/node-exporter.ClusterRole.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.ClusterRoleBinding.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.DaemonSet.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.PodSecurityPolicy.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.Service.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.ServiceAccount.yaml
charts/sourcegraph/templates/prometheus/prometheus.ConfigMap.yaml
charts/sourcegraph/tests/nodeExporter_test.yaml
charts/sourcegraph/values.yaml

_See https://github.com/sourcegraph/sourcegraph/pull/43107 for more context._
This PR adds [node-exporter](https://github.com/prometheus/node_exporter) to our kubernetes deployment.  Node-exporter is a Prometheus exporter that exposes machine-level metrics (as opposed to [cadvisor](https://github.com/google/cadvisor), which exposes _container_-level metrics). Node-exporter can expose metrics like [disk i/o stats](https://github.com/sourcegraph/sourcegraph/pull/43070), which can help us scale Sourcegraph deployments for our larger customers. 
---
Overall Node-exporter's deployement is quite similar to our existing [cadvisor](https://github.com/sourcegraph/deploy-sourcegraph-helm/tree/main/charts/sourcegraph/templates/cadvisor) configuraion:
- It needs to **run as a daemonset** (where each …

add node exporter daemonset

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/node-exporter/node-exporter.ClusterRole.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.ClusterRoleBinding.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.DaemonSet.yaml
charts/sourcegraph/templates/node-exporter/node-exporter.PodSecurityPolicy.yaml
charts/sourcegraph/tests/nodeExporter_test.yaml
charts/sourcegraph/values.yaml

The only purpose of node-exporter's [ServiceAccount](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/node-exporter/node-exporter.ServiceAccount.yaml) is to [bind the node-exporter pod](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/9abc264ff36ab0261f3018c395d84df9c692c606/charts/sourcegraph/templates/node-exporter/node-exporter.ClusterRole.yaml#L13) to the [PodSecurityPolicy](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/templates/node-exporter/node-exporter.PodSecurityPolicy.yaml). 
However, if the user doesn't want to use a pod security policy - there is no need to create the ClusterRole, ClusterRoleBinding, or ServiceAccounts either. 
This PR makes the following changes:
1. By default, only …

node-exporter: only render clusterrole if PSP is enabled

---

charts/sourcegraph/CHANGELOG.md

This was accidentally moved to the 4.1.x release section
- [x ] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
- [ x] Update [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md)
N/A - this is just a changelog change

changelog: move node exporter nodes to unreleased

---

charts/sourcegraph/templates/prometheus/prometheus.ConfigMap.yaml

Follows https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/5616, https://github.com/sourcegraph/deploy-sourcegraph-dogfood-k8s/pull/5613
This PR tweaks the Prometheus configuration to drop labels with an empty `nodename` parameter. 
Since https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/194, there seems to be duplicate metrics (one with an empty `nodename`, one with a `populated` one). I'm unsure of the exact cause, but I can speculate that:
- perhaps the k8s api is returning empty responses in some cases
- perhaps the metric relabelling process ends up duplicating a time series 
This PR resolves this situtation by dropping the metrics with  empty `nodename` labels.
Running on k8s.sgdev.org, see the following commits: …

prometheus: drop labels with duplicate nodename entries

---

.github/workflows/gcs_chart_publish_insiders.yml
.github/workflows/gcs_chart_publish_release.yml
.github/workflows/pr-auditor.yml

Update to actions/checkout@v3 to avoid deprecation warning
Created as part of batch change: [_Created by Sourcegraph batch change `sourcegraph-operator-dax/Upgrade_actions_checkout_v2-v3`._](https://sourcegraph.sourcegraph.com/users/sourcegraph-operator-dax/batch-changes/Upgrade_actions_checkout_v2-v3)

ci: update to actions/checkout@v3

---

TEST.md
charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml

Customer reported issue rendering Jaeger Deployment template when specifying an image pull secret:
1. `helm lint charts/sourcegraph/.` ✅ 
2. `helm unittest --helm3 ./charts/sourcegraph/.` ✅ 
3. `helm template . --values override.yaml` ✅ 
override.yaml:
```
sourcegraph:
imagePullSecrets:
- name: docker-pullsecret
jaeger:
enabled: true
serviceAccount:
name: jaeger
```

fix for rendering jaeger Deployment when specifying an image pull secret

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/otel-collector/otel-agent.DaemonSet.yaml
charts/sourcegraph/tests/otelAgentHostPort_test.yaml
charts/sourcegraph/values.yaml

Deploying the Helm chart multiple times on a single cluster will currently fail with OpenTelemetry enabled:
- The agent DaemonSet opens a `hostPort`, because services producing spans have to target the DaemonSet pod running on the same node as that service. This is achieved by setting `OTEL_EXPORTER_OTLP_ENDPOINT` to `hostIP` and then targeting the gRPC port (4317).
- A `hostPort` needs to be unique on each node.
- When deploying an additional instance of Sourcegraph with the Helm chart, it will try to deploy the DaemonSet, but the preexisting deployment already uses the `hostPort`, so the additional deployment fails.
- The existing implementation can only disable OpenTelemetry entirely, which drops tracing support.
This PR allows overriding the `hostPort`s of the agent DaemonSet, which …

otel: support custom `hostPort` values for agents

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/otel-collector/otel-agent.DaemonSet.yaml
charts/sourcegraph/templates/otel-collector/otel-agent.ServiceAccount.yaml
charts/sourcegraph/templates/otel-collector/otel-collector.Deployment.yaml
charts/sourcegraph/templates/otel-collector/otel-collector.ServiceAccount.yaml
charts/sourcegraph/tests/__snapshot__/serviceAccountAnnotations_test.yaml.snap
charts/sourcegraph/tests/__snapshot__/serviceAccounts_test.yaml.snap
charts/sourcegraph/tests/serviceAccountAnnotations_test.yaml
charts/sourcegraph/tests/serviceAccounts_test.yaml
charts/sourcegraph/values.yaml

context: https://github.com/sourcegraph/cloud/pull/233/files#diff-de28fac124e846e1aa56e057edeec7edc7cab80be1a00512a5660d02e5cacfb8R65-R72
we need workload identity for otel-collector so we can export traces to GCP Trace
added test and CI

sourcegraph: add service account support for otel

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/symbols/symbols.StatefulSet.yaml

This PR fixes a bug introduced into the helm charts as a result of changes in `sourcegraph/sourcegraph`, TL;DR `CACHE_DIR` was renamed to `SYMBOLS_CACHE_DIR`. This causes some symbols searches to fail to resolve --
You can add the following to your `override.yaml`:
```yaml
env:
- name: CACHE_DIR
value: null
- name: SYMBOLS_CACHE_DIR
value: /mnt/cache/$(POD_NAME)
```
and apply the changes to your cluster with --
```
helm -n sourcegraph upgrade --install -f override.yaml --version 4.5.1 sourcegraph sourcegraph/sourcegraph
```

change CACHE_DIR env var to SYMBOLS_CACHE_DIR in symbols template

---

charts/sourcegraph/templates/searcher/searcher.StatefulSet.yaml
charts/sourcegraph/templates/symbols/symbols.StatefulSet.yaml

This change is proposed because:
1. Symbols and Searcher were switched from Deployment Controllers to StatefulSets in [PR 242](https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/242)
2. Kubernetes [introduced](https://kubernetes.io/blog/2021/08/27/minreadyseconds-statefulsets/) StatefulSet support for the `minReadySeconds` configuration in release v1.22
3. Sourcegraph docs advertise [support for Kubernetes 1.19+](https://docs.sourcegraph.com/admin/deploy/kubernetes#prerequisites), so we shouldn't ship default k8s configurations that are unsupported in 1.19
Alternative solutions could involve making `minReadySeconds` a configurable, optional helm value for these STSs, or possibly reverting these two services back to Deployments if we absolutely want to enforce this setting. The …

removed minReadySeconds settings from Searcher and Symbols

---

scripts/ci/helm-unittest.sh

The helm-unittest library was recently updated. 
This change pins an older, working version until the newer version can be checked and tests updated accordingly 
Tests pass locally

Pin helm-unittest version

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Service.yaml
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.StatefulSet.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Service.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.StatefulSet.yaml
charts/sourcegraph/templates/pgsql/pgsql.Service.yaml
charts/sourcegraph/templates/pgsql/pgsql.StatefulSet.yaml

Fixes https://github.com/sourcegraph/sourcegraph/issues/51175.
Ultimately this change is minor, but may prevent confusion.
The port name and targetPort name are not actually used for anything besides human readability to my knowledge and there are no known issues with the current manifest. This does bring things in line with the convention in use in codeinsights-db service file though, and will eliminate possible confusion by readers
[Codeinsights manifest](https://sourcegraph.com/github.com/sourcegraph/deploy-sourcegraph-helm@release/5.0/-/blob/charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Service.yaml?L23:5)

Fix port naming in codeintel-db service spec

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph-executor/README.md
charts/sourcegraph-executor/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/Chart.yaml
charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Cherry pick of the release-publishing commit
- [NA] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
- [NA] Update [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md)
NA

release: sourcegraph@5.0.4 (#284)

---

charts/sourcegraph-executor/Chart.yaml
charts/sourcegraph/templates/embeddings/embeddings.Deployment.yaml

Incorrect indentation of metadata causes warnings on 5.0.4 when embeddings are enabled.
Unfortunately for customers using Argo validation this causes the deployment to fail.
Closes #287 
Tested locally; embeddings service works, helm warnings gone

fix: Embeddings indentation (#288)

---

charts/sourcegraph/Chart.yaml

Previous PR https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/289 incorrectly bumped version for sourcegraph-migrator chart instead of sourcegraph chart
only version change

fix: Sourcegraph chart hotfix version

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml

Seems like the release tooling has an issue where it doesn't update the Chart.yaml values for the executor charts.
Manual inspection + CI

Update Executor Chart.yaml values for 5.1.4

---

charts/sourcegraph/examples/gcp/README.md
charts/sourcegraph/examples/gcp/override.yaml

https://sourcegraph.slack.com/archives/C89KCDK5J/p1689091378857949
https://github.com/sourcegraph/log/pull/61, https://github.com/sourcegraph/sourcegraph/pull/54793
tested on cloud

sourcegraph: add `json_gcp` log format in gcp example overrides

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/k8s/Chart.yaml

Update executors versions in `Chart.yaml` files. These values seem to be missed by the release tooling.

Update executors charts.yaml versions

---

TEST.md
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/qdrant/qdrant.ConfigMap.yaml
charts/sourcegraph/templates/qdrant/qdrant.Deployment.yaml
charts/sourcegraph/templates/qdrant/qdrant.PersistentVolumeClaim.yaml
charts/sourcegraph/templates/qdrant/qdrant.Service.yaml
charts/sourcegraph/templates/qdrant/qdrant.ServiceAccount.yaml
charts/sourcegraph/templates/qdrant/qdrant.StatefulSet.yaml
charts/sourcegraph/values.yaml

This implements helm charts to add a Qdrant deployment to our cloud deployments. The intent is to replace the `embeddings` service entirely and to stop depending on blobstore for embeddings storage. 
I ran the cluster locally, ensuring that I can generate and search embeddings with Qdrant. 
I tested with the following `override.yaml`:
```yaml
storageClass:
create: false
name: standard
sourcegraph:
localDevMode: true
image:
defaultTag: insiders
useGlobalTagAsDefault: true
qdrant:
enabled: true
gitserver:
env:
SRC_REPOS_DESIRED_PERCENT_FREE:
value: "0"
frontend:
env:
QDRANT_ENDPOINT:
value: "qdrant:6334"
```

Qdrant: add helm charts

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/qdrant/qdrant.StatefulSet.yaml
charts/sourcegraph/values.yaml
override.yaml

Apparently `strategy` is not a valid field for `StatefulSet` (only `Deployment`). I caught this when trying to port the rendered helm template to the dotcom deployment, which uses `kubectl apply` rather than `helm upgrade`. `kubectl apply` returns a validation error for that field.
This fixes `strategy` and two other invalid fields which are ignored with helm, but get caught by the `kubectl apply` validator. 
Ran the cluster locally, inspected the running service  to ensure it had an update strategy of `RollingUpdate`

Qdrant: fix invalid field

---

charts/sourcegraph-executor/dind/Chart.yaml
charts/sourcegraph-executor/dind/README.md
charts/sourcegraph-executor/dind/values.yaml
charts/sourcegraph-executor/k8s/Chart.yaml
charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml
charts/sourcegraph-migrator/Chart.yaml
charts/sourcegraph-migrator/README.md
charts/sourcegraph-migrator/values.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/Chart.yaml
charts/sourcegraph/examples/subchart/Chart.yaml

 5.2.3 changelog and cherry picked commit

---

charts/sourcegraph/templates/otel-collector/otel-agent.ServiceAccount.yaml
charts/sourcegraph/templates/otel-collector/otel-collector.ServiceAccount.yaml

with below override to enable otel SA
```yaml
openTelemetry:
gateway:
serviceAccount:
create: true
```
you got
```
Error: YAML parse error on sourcegraph/templates/otel-collector/otel-collector.ServiceAccount.yaml: error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
```
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
labels:
category: rbac
deploy: sourcegraph
app.kubernetes.io/component: otel-collector
annotations:
iam.gke.io/gcp-service-account: src-4b18e57abef3ef40@src-747bc765eb31a4873e4b.iam.gserviceaccount.comname: otel-collector
```
actually surprise helm unit test doesn't catch the same error
no more error

sourcegraph: fix otel service account tmpl

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/syntect-server/syntect-server.Service.yaml

Due to our prom config, service without specific labels are ignroed and won't be scraped.
https://github.com/sourcegraph/deploy-sourcegraph/blob/242be7c36d7b1b2481d62a2a95b07053311cdf54/base/prometheus/prometheus.ConfigMap.yaml#L131-L134
This PR added the missing required annotations, `sourcegraph.prometheus/scrape=true`, to `syntect-server` svc.
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/5faa5c5d577e96657dd33961b5c9776eec7665e2/charts/sourcegraph/templates/searcher/searcher.Service.yaml#L4-L10
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/5faa5c5d577e96657dd33961b5c9776eec7665e2/charts/sourcegraph/templates/syntect-server/syntect-server.Service.yaml#L4-L7
```
helm upgrade --install --create-namespace -n sourcegraph -f ./override.yaml sourcegraph …
```

sourcegraph: fix unable to scrape syntect-server metrics

---

charts/sourcegraph-migrator/templates/migrator/sourcegraph-migrator.Job.yaml
charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

Allow for `volumeMounts` in the frontend init container.
* Allows mounting TLS certificates needed to establish encrypted TLS connections to PostgreSQL databases. 
Values can be set in a override file as follows:
```yaml
frontend:
extraVolumes:
- name: migrator-tls
secret:
secretName: migrator-tls-secret
migrator:
extraVolumeMounts:
- name: migrator-tls
mountPath: /etc/tls
readOnly: true
env:
PGSSLCERT:
value: /etc/tls/tls.crt
PGSSLKEY:
value: /etc/tls/tls.key
```
Manual test and Helm lint

Add volumeMounts option for frontend init container

---

charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/templates/executor.ConfigMap.yaml
charts/sourcegraph-executor/k8s/templates/executor.Deployment.yaml
charts/sourcegraph-executor/k8s/templates/executor.PersistentVolumeClaim.yaml
charts/sourcegraph-executor/k8s/templates/executor.Secret.yaml
charts/sourcegraph-executor/k8s/templates/executor.Service.yaml
charts/sourcegraph-executor/k8s/values.yaml

- Backport for #403 
- Fix for https://github.com/sourcegraph/deploy-sourcegraph-helm/issues/402
- Removed the `Values.executor.enabled`  boolean
- if you don't want to enable executors, you probably shouldn't be deploying this helm chart to begin with...
- deploying this chart with `executor.enabled=false` will only deploy RBAC resources (unless `executor.configureRbac=false` as well)
- templated out `sourcegraph/sourcegraph-executor-k8s` using both `frontendPassword` and `frontendExistingSecret`

Added executor.frontendExistingSecret for k8s executor helm chart

---

release.yaml

The skips were added during testing early on
ran the release tooling locally without the skips and it succeeded

rfc-795 relase manifest: the skips are not needed anymore

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml

From #inc-270
We should try to match the config on dot-com and keep our learnings

Update redis health checks based on dot-com

---

.github/workflows/gcs_chart_publish_release.yml

Adds the new `release-` syntax to the GH action that publishes Helm charts.
N/A

Fix: helm chart publishing action

---

charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/prometheus/prometheus.Deployment.yaml

interesting thing could happy if we don't track this in manifest
- if using `helm template | kubectl apply` to deploy
- scale these deploy to 0
- `helm template | kubectl apply` will not scale it back to 1
CI

sourcegraph: make sure we set replicacount

---

release.yaml

Add step to check that release captain is authenticated via `gh` during the release process.

release: add check for gh auth status

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml

Should resolve https://github.com/sourcegraph/deploy-sourcegraph-helm/issues/457
Tested locally

Fix: Redis Readiness Check with password

---

release.yaml

Fixing so we don't run into the issue with non-interpolated strings.
Local test.

release: quote commit sha in release config

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml

fix: redis readiness probe needs to export the password env var

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml

INC-305
Reverts sourcegraph/deploy-sourcegraph-helm#470
CI

Revert "fix: redis readiness probe needs to export the password env var"

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml
charts/sourcegraph/templates/redis/redis-store.Deployment.yaml

does
Tested manually on kind. Tested against both having a password, and having no password set.

Fix: Check for the existence of a redis password, not config file. 

---

.github/workflows/release-amis.yml

Since we moved this action from the monorepo to here, we need to change it to match the semantics of this repo. 
The monorepo had "actual" github releases, but this repo only has tagged commits that contain the release artifact. 
This PR changes the action so that it runs on push of `v<VERSION_NUMBER>` instead of creation of a release. 
Run manually

fix(ci): deploy-sourcegraph-helm doesn't have releases, just tags

---

charts/sourcegraph-appliance/templates/deployment.yaml
charts/sourcegraph-appliance/templates/service.yaml

It was already using simple `app: sourcegraph-appliance`, but this label wasn't on the pod template. Add it, and also remove the rest of the service selector just because we can. This simplifies the code we need to write on the appliance side.
Also simplify the deployment metadata.name, so that it can be well-known, independent of the helm release name, like the other resources here (since the release will be a singleton in namespace scope).
Relates to https://linear.app/sourcegraph/issue/REL-78/when-sourcegraph-frontend-is-down-a-user-trying-to-access-sourcegraph but does not close it.
Templated out the helm chart, observed the default renders.

fix(appliance): fix service selector

---

charts/sourcegraph-appliance/Chart.yaml
charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/templates/deployment-frontend.yaml
charts/sourcegraph-appliance/templates/service-backend.yaml
charts/sourcegraph-appliance/values.yaml

- Add deployment for appliance-frontend.
- re-point frontend service at this frontend, not the appliance backend
- Add a service for the backend, and reference it in the frontend's env
vars.
- Fix indentation of appliance backend label.
- Hardcode appliance backend container port - there's no need to change
it, this is just error-prone.
- Fix deployment name for self-update, and add the frontend to the
self-update list (see
https://linear.app/sourcegraph/issue/REL-302/self-update-should-update-appliance-frontend-too)
- Bump chart app version
Relates to https://linear.app/sourcegraph/issue/REL-293/appliance-is-packaged-in-containers-for-production and https://linear.app/sourcegraph/issue/REL-305/kick-the-tires-with-a-realistic-ingress, but does not close them.
See comments in …

appliance: add frontend resources

---

charts/sourcegraph/templates/redis/redis-cache.Deployment.yaml

The pods get killed too quickly leading to SG repeated thrashing the redis pods with connections and then the probe can't connect which kills the pod ... leading to SG thrashing the pod again.
related: https://github.com/sourcegraph/deploy-sourcegraph-cloud/pull/18681
closes DINF-163
Deployment

redis: adjust failureThreshold

---

charts/sourcegraph-appliance/Chart.yaml
charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml

Once this is merged, let's remove the newly no-op declarations of this default from https://www.notion.so/sourcegraph/Appliance-User-Manual-8f9f8ce28aba440a8134d295890b824a.
`helm template`

feat(appliance): enable ingress by default

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/values.yaml

You can't interpolate in values.yaml, even with things set in Chart.yaml. The old code causes a literal `{{ .Chart.AppVersion }}` to appear in image tags, which is invalid.
E2E tested the appliance, including deploying SG, using the following command to deploy:
```
helm upgrade --install --namespace test \
--set noResourceRestrictions=true \
appliance ./charts/sourcegraph-appliance
```

fix(appliance): chart version interpolation

---

charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/templates/deployment.yaml
charts/sourcegraph-appliance/values.yaml

Requires the admin to create a particular configmap first:
```
kubectl create configmap pinned-releases --from-file releases.json
```
`releases.json` must be formed like a release registry response, the same schema as what is returned by `curl
https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph`.
Relates to https://linear.app/sourcegraph/issue/REL-200/airgap-fallback-for-appliance-dependency-on-release-registry, https://linear.app/sourcegraph/issue/REL-268/airgap-fallback-for-appliance-self-update, and https://github.com/sourcegraph/sourcegraph/pull/64441.
If approved, I'll edit the appliance user manual to document this configmap creation process for airgap users.
Manual verification with and without the new flag.

feat(appliance): airgap fallback

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/syntactic-code-intel/worker.Deployment.yaml
charts/sourcegraph/templates/syntactic-code-intel/worker.Service.yaml
charts/sourcegraph/templates/syntactic-code-intel/worker.ServiceAccount.yaml
charts/sourcegraph/values.yaml

Fixes GRAPH-786
This adds experimental syntactic worker to our helm charts.
The configuration is similar in structure to the precise code intel worker (and was copied from it) but has a few modifications, removing unused env variables.
Resource usage is so far copied from precise worker but it's not scientific - we'll adjust the ceiling and number of workers after testing on real instances.
- Tested manually on my local kind cluster

Syntactic code intel worker deployment

---

charts/sourcegraph-appliance/Chart.yaml
charts/sourcegraph-appliance/README.md
charts/sourcegraph-appliance/templates/deployment-frontend.yaml
charts/sourcegraph-appliance/templates/deployment.yaml
charts/sourcegraph-appliance/values.yaml
release.yaml

**appliance: value schema conforms to what sg-ops expects**
sg-ops-update-images expects a certain value schema in order to agree to operate on it. This includes tags that contain digests.
**release: update appliance artifacts**
Closes https://linear.app/sourcegraph/issue/REL-322/appliance-helm-chart-should-be-versioned
1. Check out https://github.com/sourcegraph/sourcegraph/pull/64512
2. Build sg: `go build -o sg ./dev/sg`
3. In this repository, run:
```
export registry=us-central1-docker.pkg.dev/sourcegraph-ci/rfc795-internal
export DOCKER_USERNAME=<value from 1p>
export DOCKER_PASSWORD=<value from 1p>
/path/to/custom/sg ops update-images \
-t 5.6.185 \
-k helm \
--registry "${registry}" \
--docker-username $DOCKER_USERNAME \
--docker-password $DOCKER_PASSWORD \ …
```

feat(appliance): update image tags and chart version on release

---

.gitignore
charts/sourcegraph-appliance/templates/deployment-frontend.yaml

Change nginx container port to `8080` to avoid permission issues.
See https://linear.app/sourcegraph/issue/REL-372/nginx-port-permissions-issue
Tested locally

fix(appliance): change nginx container port to 8080

---

charts/sourcegraph/templates/syntactic-code-intel/worker.Deployment.yaml

This was a mistake, the _ADDR env variable should always be set, not just when blobstore is enabled.
- N/A

Set syntactic address unconditionally

---

charts/sourcegraph-executor/k8s/templates/executor.Role.yaml

`KUBERNETES_SINGLE_JOB_POD` mode was enabled by default in v5.6 with [PR 64088](https://github.com/sourcegraph/sourcegraph-public-snapshot/pull/64088) which includes a new requirement to manage ephemeral k8s Secrets.
N/A

Updated RBAC for KUBERNETES_SINGLE_JOB_POD mode

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/templates/otel-collector/otel-agent.DaemonSet.yaml
charts/sourcegraph/templates/otel-collector/otel-collector.Deployment.yaml
charts/sourcegraph/values.yaml

Run the otel-collector and otel-agent containers as the `sourcegraph` user rather than `root`.
One of our customers is asking us to ensure that containers don't run as root.
I haven't been able to identify the original reason why these containers were running as root, so it seems that this was simply an oversight when the containers were originally created. This PR drops the `runAs` user + group IDs to `sourcegraph:sourcegraph`.
otel-collector seems to be broken currently, due to incorrect configuration with jaeger - see https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/542 + linked slack discussion for a fix.
Testing locally requires setting `jaeger.enabled: true` in values.yaml, and applying the fix [linked above](https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/542) …

Ensure that otel-collector and otel-agent run as sourcegraph user

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

This probably shouldn't be merged as-is - it's a rough PR to give an indication of the fix in https://sourcegraph.slack.com/archives/C02E4HE42BX/p1724672390421409
Should these new parameters be replicated in [jaeger.Deployment.yaml](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/8803c0523ff153c587888d180d5e3eb7069d6ef4/charts/sourcegraph/templates/jaeger/jaeger.Deployment.yaml#L56) too?
Tested manually by @marcleblanc2

Add port overrides to jaeger default args

---

charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

In all places we include the databaseAuth we add it first in the env list, except for the frontend pod. This updates it to be consistently first.
Context: For multitenant deployments we want to override the DB user the frontend uses to connect such that it is different to the migrator. This allows us to do that.
Test Plan: TODO Need some guidence here. I don't think this should break any existing use cases, except if someone previously tried to override db envvars and it didn't work. Now it will work.
cc @eseliger 
Part of https://linear.app/sourcegraph/issue/SRC-593/figure-out-how-to-separate-rls-user-and-migrations-user

frontend: specify databaseAuth consistently first in env

---

charts/sourcegraph/templates/frontend/sourcegraph-frontend.Deployment.yaml

this can result in duplicated env var and cause weird behaviour.
n/a

sourcegraph: do not include frontend env var in migrator container

---

charts/sourcegraph/templates/grafana/grafana.ConfigMap.yaml

For [PS-83: Create pgsql datasource in Grafana](https://linear.app/sourcegraph/issue/PS-83/create-pgsql-datasource-in-grafana)
Tested on test instance for upgrades and new installs, with and without the env vars configured
I tried to change the existing ConfigMap just mounted as a single file inside the directory, so then I could just add Postgres via a separate ConfigMap via subDir mount, but that threw Grafana for a loop because the datasources.yml file is not declarative (ex. Terraform), but just an input ingestion method to Grafana's config state (maintained in a MongoDB inside the Grafana container?), and when the datasources.yml file gets a new inode on an existing instance, Grafana fails to start up, because we have default:true on Prometheus, so Grafana seeing the same Prometheus …

Adding pgsql datasource for Grafana

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/grafana/grafana.ConfigMap.yaml
charts/sourcegraph/templates/grafana/grafana.StatefulSet.yaml
charts/sourcegraph/templates/grafana/grafana.pgsql.Secret.yaml
charts/sourcegraph/values.yaml

Manual testing on test instance, with and without the config defined

Add Kubernetes secret config for Grafana

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/_worker.tpl
charts/sourcegraph/templates/worker/worker.Deployment.yaml
charts/sourcegraph/tests/worker_test.yaml
charts/sourcegraph/values.yaml

ref CLO-1023
https://sourcegraph.com/docs/admin/workers#3-split-jobs-and-scale-independently
`worker` is not really horizontally scalable, and it requires manually creating additionally `worker` deployments with the correct `WORKER_JOB_ALLOWLIST` and `WORKER_JOB_BLOCKLIST` environment variable.
This PR added native support for managing multiple worker deployment through helm template.
By default, it will work as is to day with a single `worker` deployment. To enable additional dedicated worker, user can specify the following overrides:
```yml
worker:
replicas:
- jobs:
- workspaces-reconciler
- jobs:
- codeintel-upload-janitor
```
This will create 3 distinct worker deployment (`worker`, `worker-0`, and `worker-1`) with the correct `WORKER_JOB_*` env var. Additinoally, we also support …

feat(sourcegraph): add support to scale worker horizontally

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/worker/worker.Deployment.yaml
charts/sourcegraph/tests/worker_test.yaml
charts/sourcegraph/values.yaml

when having replicas, the env var `WORKER_JOB_BLOCKLIST` is now managed by the template. hence we need an override so we can merge them together.
unit tests
tested with below overrides in a kind cluster
```
worker:
blocklist:
- "aggregated-users-statistics"
replicas:
- jobs:
- workspaces-reconciler
resources:
limits:
cpu: 200m
memory: 256Mi
requests:
cpu: 200m
memory: 256Mi
```

fix(sourcegraph): unable to block job when running replicas

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Fix image tags for new DBs that were missed by the update tooling.
Local/CI

fix(rel): fix database image tags for 5.10.0 release

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Update image tags from insiders to a know version. `sg ops` will not pickup insiders and misses the tag in our release workflow.
CI - manual test

fix(rel): update image tags from insiders

---

charts/sourcegraph/README.md
charts/sourcegraph/values.yaml

Even with the version, `sg ops` won't replace the sha tag if none is present.
CI and local testing

fix(rel): PG images add SHA for image tag

---

.github/workflows/helm_lint_test.yml
release.yaml

Add a step to our build process that creates a PR with the latest release version to merge back into `main`.
Also updates broken Github action Python dependency in CI. 
- [NA] Follow the [manual testing process](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/TEST.md)
- [NA] Update [changelog](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/CHANGELOG.md)
- [NA] Update [Kubernetes update doc](https://docs.sourcegraph.com/admin/updates/kubernetes)
Part of CI steps during release process.

feat(rel): add steps to update main with latest versions

---

TEST.md
charts/sourcegraph/tests/checksum_test.yaml
charts/sourcegraph/tests/codeInsightsDBAdditionalConfig_test.yaml
charts/sourcegraph/tests/codeIntelDBAdditionalConfig_test.yaml
charts/sourcegraph/tests/defaultTagPrefix_test.yaml
charts/sourcegraph/tests/localDevMode_test.yaml
charts/sourcegraph/tests/nodeExporter_test.yaml
charts/sourcegraph/tests/otelCollectorJaeger_test.yaml
charts/sourcegraph/tests/pgsqlAdditionalConfig_test.yaml
charts/sourcegraph/tests/pgsqlAuth_test.yaml
charts/sourcegraph/tests/storageClass_test.yaml
charts/sourcegraph/tests/worker_test.yaml
scripts/ci/helm-unittest.sh

- Switch to the canonical helm unittest isntead of an outdated fork.
- Update the tests to work with latest syntax.
1. uninstall the outdated helm unittest fork: `helm plugin uninstall unittest`
2. install the canonical tool: `helm plugin install https://github.com/helm-unittest/helm-unittest`
3. run the unit tests: `helm unittest ./charts/sourcegraph/.`

Update unit tests to be current with most recent helm unittest syntax

---

charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/values.yaml

Since [PR 2456](https://github.com/sourcegraph/sourcegraph/pull/2456) in the Sourcegraph repo, support for the default value of -1 for  the `KUBERNETES_RUN_AS_USER` and `KUBERNETES_RUN_AS_GROUP` Executor environment variables has been removed - those environment variables now require either blank values or non-negative integers in the range [0, 2147483647], to match the range for Unix UIDs and GIDs.
This PR updates `charts/sourcegraph-executor/k8s/values.yaml` so that `runAsUser` and `runAsGroup` are commented out, with comments to explain that the user can uncomment them to use them. Having those settings commented out causes `KUBERNETES_RUN_AS_USER` and `KUBERNETES_RUN_AS_GROUP` in `charts/sourcegraph-executor/k8s/templates/executor.ConfigMap.yaml` to be blank, which is the new default …

Comment out runAsUser and runAsGroup in values.yaml

---

charts/sourcegraph-migrator/templates/_helpers.tpl
charts/sourcegraph/README.md
charts/sourcegraph/examples/external-databases/README.md
charts/sourcegraph/templates/_helpers.tpl
charts/sourcegraph/templates/codeinsights-db/codeinsights-db.Secret.yaml
charts/sourcegraph/templates/codeintel-db/codeintel-db.Secret.yaml
charts/sourcegraph/templates/pgsql/pgsql.Secret.yaml
charts/sourcegraph/tests/__snapshot__/checksum_test.yaml.snap
charts/sourcegraph/tests/__snapshot__/pgsqlAuth_test.yaml.snap
charts/sourcegraph/values.yaml

[REL-638](https://linear.app/sourcegraph/issue/REL-638/configure-aws-rds-databases-for-tls-connections-in-helm-chart)
raised issues that this flag did not get mentioned in the docs where a
customer wanted to use TLS. It also outlined the recommended fixes that
this commit implements.
This PR has an accompanying [docs PR](https://github.com/sourcegraph/docs/pull/900) 
Manually test this out? Would require spinning up an RDS instance or something, but that's fine.
I'm in the process of doing so now.

fix: add references to sslmode for postgres dbs

---

charts/sourcegraph/templates/_helpers.tpl

regression from https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/617
it's now rendering `_SSLMODE` twice in the grafana sts
CI

fix(sourcegraph): do not render SSLMODE twice for grafana sts

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/frontend/sourcegraph-frontend.PodDisruptionBudget.yaml
charts/sourcegraph/tests/podDisruptionBudget_test.yaml

fix: frontend PodDisruptionBudget

---

charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/templates/executor.Deployment.yaml
charts/sourcegraph-executor/k8s/values.yaml

The start of a resolution for [REL-690](https://linear.app/sourcegraph/issue/REL-690/add-runasuser-runasgroup-fsgroup-to-executor-helm-chart). 
Need to test this out to see how it works. There are sample overrides in [this thread](https://sourcegraph.slack.com/archives/C0418GDBT7S/p1738581012896529?thread_ts=1738580801.517539&cid=C0418GDBT7S)
Run the example overrides from the thread and see if the executor runs and doesn't fail. In particular we want a _named_ user that is not privileged.

feat: add runAsUser and runAsGroup to executor

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/templates/gitserver/gitserver.StatefulSet.yaml

This adds a startup probe to gitserver so that it's not immediately killed while it's starting up and migrating the on-disk format for repos.
Passed linters, ran it locally, plan to exercise it when we deploy to s2 and dotcom.

add gitserver startup probe

---

.github/workflows/checkov.yml

Add checkov scan for this repo to scan for vuln in infra.
- CI 🟢 
- CI github action should be actively executing on all pull request

chore: add checkov scan script

---

charts/sourcegraph/examples/prometheus/README.md
charts/sourcegraph/examples/prometheus/prometheus-override-k3s.ConfigMap.yaml

Linear issue: [REL-809: Investigate why Grafana is not showing Prometheus data](https://linear.app/sourcegraph/issue/REL-809/investigate-why-grafana-is-not-showing-prometheus-data)
Tested with a customer self-hosting on k3s, and on our AMI running k3s

Add Prometheus configMap for k3s

---

charts/sourcegraph/templates/grafana/grafana.ConfigMap.yaml

For Self-hosted Analytics project
Tested on self-hosted instance

 Fix Grafana's data source config for pgsql

---

charts/sourcegraph/examples/aws/override.yaml

It's been some time since gp3 has been available, with better performance and pricing than gp2. We should update our example to reduce the chances of a customer deploying with gp2. 
https://docs.aws.amazon.com/eks/latest/userguide/create-storage-class.html
Tested in test instance

Update gp2 to gp3 in AWS storage class example

---

charts/sourcegraph/CHANGELOG.md
charts/sourcegraph/README.md
charts/sourcegraph/examples/advanced-scheduling/override.yaml
charts/sourcegraph/examples/basic/override.yaml
charts/sourcegraph/examples/common-modifications/override.yaml
charts/sourcegraph/examples/gcp/override.yaml
charts/sourcegraph/templates/searcher/searcher.StatefulSet.yaml
charts/sourcegraph/templates/symbols/symbols.Service.yaml
charts/sourcegraph/templates/symbols/symbols.ServiceAccount.yaml
charts/sourcegraph/templates/symbols/symbols.StatefulSet.yaml
charts/sourcegraph/tests/priorityClass_test.yaml
charts/sourcegraph/values.yaml

Reverts sourcegraph/deploy-sourcegraph-helm#675
```
The StatefulSet "searcher" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```
pvc template is immutable in STS and the PR changed the value. it will break for all existing deployment
Test plan: CI

Revert "Remove symbols statefulset"

---

charts/sourcegraph-executor/k8s/README.md
charts/sourcegraph-executor/k8s/templates/executor.Deployment.yaml
charts/sourcegraph-executor/k8s/values.yaml

configure resource request and limits for native k8s executors for consistency with other sourcegraph helm charts.
verified with `helm template . --show-only templates/executor.Deployment.yaml`

configure resource requests and limits for native k8s executors

---

release.yaml

Closes REL-1068
The release pipeline has been systematically failing in the `promoteToPublic.finalize` workflow with this error:
```
Warning: 1 uncommitted change
must be on a branch named differently than 'promote/release-v6.4.3889-update-main'
```
The final `github:pr` step in the `promoteToPublic.finalize` workflow was incorrectly trying to create a PR from the current branch to itself:
- **Current branch**: `promote/release-{{version}}-update-main`
- **Target branch**: `promote/release-{{version}}-update-main` ❌ (same branch!)
- **Should target**: `main` ✅
This happened because the variable `internal_branch` was set to the current branch name instead of the intended target branch.
This will have to be tested on a release

Fix(release): promoteToPublic.finalize github:pr update main target bug

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/frontend/sourcegraph-frontend.RoleBinding.yaml
charts/sourcegraph/values.yaml

Ran `helm template`, `helm lint`, and `helm unittest`, all passed

Create Values.frontend.createRoleBinding to allow it to be disabled

---

charts/sourcegraph/README.md
charts/sourcegraph/templates/tests/test-connection.yaml
charts/sourcegraph/values.yaml

Allow self-hosted customers to disable the sg-test-connection pod, similar to how the Cloud instances do (https://github.com/sourcegraph/cloud/pull/8)
Ran `helm template`, `helm lint`, and `helm unittest`, all passed

Create config for sgTestConnection enabled
